import { useUser } from '@clerk/nextjs';
import { type NextPage } from 'next';
import Head from 'next/head';

import { PageLoadingSpinner } from '~/components/loading-spinner';
import { Post } from '~/components/post';
import { PostCreateWizard } from '~/components/post-create-wizard';
import { api } from '~/utils/api';

const Feed = () => {
    const { data, isLoading: arePostsLoading } = api.post.getAll.useQuery();
    if (arePostsLoading) return <PageLoadingSpinner />;
    if (!data) return <div>Something went wrong</div>;

    return (
        <div className="flex flex-col border-t border-yellow-200">
            {data?.map((authorPost) => (
                <Post {...authorPost} key={authorPost.post.id} />
            ))}
        </div>
    );
};

const Home: NextPage = () => {
    const { isSignedIn, isLoaded: isUserLoaded } = useUser();

    // prefetch posts
    api.post.getAll.useQuery();

    if (!isUserLoaded) return <div />;

    return (
        <>
            <Head>
                <title>Create T3 App</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="flex h-screen justify-center">
                <div className="w-full rounded-md border-x border-yellow-200 md:max-w-2xl">
                    {isSignedIn && <PostCreateWizard />}
                    <Feed />
                </div>
            </main>
        </>
    );
};

export default Home;
